- name: install tlp and powertop
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
      - powertop
    state: present
    update_cache: true
  become: true

- name: start and enable tlp
  ansible.builtin.systemd:
    name: tlp
    state: started
    enabled: true
  become: true
