---

sign_keys:
  - https://dl.google.com/linux/linux_signing_key.pub
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg

ppas:
  - ppa:graphic-drivers
  - ppa:solaar-unifing/ppa

other_repos:
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

packages_to_install:
  - apt-transport-https
  - ca-certificates
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - endpoint-verification
  - git
  - gnupg-agent
  - google-chrome-stable
  - nvidia-driver-455
  - software-properties-common
  - solaar
  - vlc


