---

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- name: add repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ arch }}] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  become: yes

- name: install
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
  become: yes