---

apt_packages_preinstall:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg-agent
  - software-properties-common
  - snapd
  - python3-pip
  - python-is-python3

apt_packages_install:
  - vlc
  - gitk

deb_packages_install:
  - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.13.0-amd64.deb

