- name: Add items to .bash_aliases
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    line: alias {{ item.name }}='{{ item.command }}'
    state: present
    create: true
    mode: 0644
  with_items: "{{ bash_alias_items }}"

- name: Add items to .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
    create: true
    mode: 0644
  with_items: "{{ bashrc_items }}"
