- name: Install
  ansible.builtin.apt:
    name:
      - xbindkeys
      - xsel
      - xdotool
    state: present
    update_cache: true
  become: true

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0644
  with_fileglob:
    - .xbindkeysrc

- name: Apply auto start
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.xsessionrc"
    line: xbindkeys -p
    state: present
    create: true
    mode: 0644
