- name: Add ppas
  ansible.builtin.apt_repository:
    repo: ppa:solaar-unifying/ppa
    state: present
  become: true

- name: Install
  ansible.builtin.apt:
    name: solaar
    state: present
    update_cache: true
  become: true

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/autostart/"
    mode: preserve
  with_fileglob:
    - ./*
