---

- name: Install
  apt:
    name:
      - xbindkeys
      - xsel
      - xdotool
    state: latest
    update_cache: yes
  become: yes


- name: file copy
  copy:
    src: "{{ item }}"
    dest: ~/
  with_fileglob:
    - ../files/.xbindkeysrc

- name: apply
  shell: xbindkeys -p
