---

- name: disable_middle_key task
  tags: disable_middle_key
  block:
  - name: disable_middle_key, install
    apt:
      name:
        - xbindkeys
        - xsel
        - xdotool
      state: latest
      update_cache: yes
    become: yes


  - name: disable_middle_key, file copy
    copy:
      src: "{{ item }}"
      dest: ~/
    with_fileglob:
      - ../files/.xbindkeysrc

  - name: disable_middle_key, auto apply
    lineinfile:
      dest: ~/.xsessionrc
      line: xbindkeys -p
      state: present
      create: yes
