---

- name: install tlp and powertop
  ansible.builtin.apt: 
    name: 
      - tlp
      - tlp-rdw
      - powertop
    state: present
    update_cache: yes
  become: yes

- name: start and enable tlp
  ansible.builtin.systemd:
    name: tlp
    state: started
    enabled: yes
  become: yes