---

- name: Add ppas
  apt_repository:
    repo: ppa:atareao/atareao
    state: present
  become: yes

- name: Install
  ansible.builtin.apt:
    name: touchpad-indicator
    state: present
    update_cache: yes
  become: yes
