---

- name: Get gpg
  shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
  args:
    warn: no

- name: Install gpg
  shell: install -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/trusted.gpg.d/
  become: yes

- name: Add source
  shell: sh -c 'echo "deb [arch={{ arch }} signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  become: yes

- name: Install code
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: yes
  become: yes
