- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true

- name: Intall pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
  become: true
