- name: Add ppas
  apt_repository:
    repo: ppa:atareao/atareao
    state: present
  become: true

- name: Install
  ansible.builtin.apt:
    name: touchpad-indicator
    state: present
    update_cache: true
  become: true
