---

- name: install
  ansible.builtin.apt:
    name: fzf
    state: present
    update_cache: yes
  become: yes

- name: enable autocomplete and key bindings
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"

    state: present
    create: yes
    mode: 0644
  with_items:
    - "# fzf settings"
    - "source /usr/share/doc/fzf/examples/key-bindings.bash"
    - "source /usr/share/doc/fzf/examples/completion.bash"
