- name: add to .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    create: true
    mode: 0644
    marker: "# {mark} ros_localhost_only"
    block: |
      if [ -f ~/.ros_localhost_only ]; then . ~/.ros_localhost_only; fi

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0644
  with_fileglob:
    - .ros_localhost_only
