---

- name: add to .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "if [ -f ~/.ros_localhost_only ]; then . ~/.ros_localhost_only; fi"
    state: present
    create: yes
    mode: 0644

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0644
  with_fileglob:
    - .ros_localhost_only
