- hosts: localhost
  connection: local
  become: false
  vars_files:
    - ./vars.yml
  roles:
    # system
    - { role: add_bash_aliases, tags: [add_bash_aliases] }
    - { role: disable_paste_middle_key, tags: [disable_paste_middle_key] }
    # - { role: nvidia_driver, tags: [nvidia_driver] }
    - { role: ros_localhost_only, tags: [ros_localhost_only] }
    - { role: swapfile, tags: [swapfile] }
    # - { role: user_dirs_english, tags: [user_dirs_english] }
    # application
    - { role: install_apt_pip, tags: [install_apt_pip] }
    - { role: nanorc, tags: [nanorc] }
    - { role: slack, tags: [slack] }
    - { role: solaar, tags: [solaar] }
    - { role: tlp_powertop, tags: [tlp_powertop] }
    - { role: touchpad_indicator, tags: [touchpad_indicator] }

    # from autoware.ecu_system_setup
    - { role: autoware.ecu_system_setup.fzf, tags: [fzf] }
    - { role: autoware.ecu_system_setup.git_common, tags: [git_common] }
    - { role: autoware.ecu_system_setup.google_chrome, tags: [google_chrome] }
    - { role: autoware.ecu_system_setup.keyboard, tags: [keyboard] }
    - { role: autoware.ecu_system_setup.vscode, tags: [vscode] }
