# common
arch: amd64

# add_bash_settings
bash_alias_items:
  - { name: gitka, command: gitk --all & }
  # prettier-ignore
  - { name: rosbag2_toggle_pause, command: ros2 service call /rosbag2_player/toggle_paused rosbag2_interfaces/srv/TogglePaused }
  # yamllint disable rule:quoted-strings
  # prettier-ignore
  - { name: rosdep-install, command: "rosdep install -iry --from-paths src --rosdistro ${ROS_DISTRO}" }

bashrc_items:
  - export RCUTILS_COLORIZED_OUTPUT=1
  - 'export RCUTILS_CONSOLE_OUTPUT_FORMAT="[{severity} {time}] [{name}] {function_name}(): {message}"'

# install_apt_pip
apt_packages:
  - curl
  - snapd
  - vlc
  - python3-pip
  - simplescreenrecorder
  - python-is-python3

pip_packages:
  - cpplint
  - ansible-lint
  - pre-commit

# nvidia_driver
nvidia_autoinstall: true
nvidia_version: 460

# slack
slack_version: 4.26.1

# autoware.ecu_system_setup.keyboard
keyboard_layout_file: ./files/keyboard

# autoware.ecu_system_setup.git-common
git_config_items:
  - { name: user.name, value: h-ohta }
  - { name: user.email, value: hiroki.ota@tier4.jp }
  - { name: color.ui, value: true }
  - { name: core.editor, value: nano }
  - { name: alias.chk, value: checkout }
  - { name: alias.fetchpt, value: fetch --prune --tags }
  - { name: alias.commits, value: commit --signoff }
  # yamllint disable rule:quoted-strings
  - { name: "url.git@github.com:.insteadOf", value: "https://github.com/" }
