---
# common
arch: "amd64"

# git-common
git_config_items:
  - { name: user.name, value: h-ohta }
  - { name: user.email, value: hiroki.ota@tier4.jp }
  - { name: color.ui, value: true}
  - { name: core.editor, value: nano}
  - { name: alias.chk, value: checkout}
  - { name: alias.fetchpt, value: fetch --prune --tags}

# install-apt-pip
apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg-agent
  - software-properties-common
  - snapd
  - python3-pip
  - python-is-python3
  - vlc

pip_packages:
  - cpplint
  - ansible-lint

# nvidia-driver
nvidia_autoinstall: false
nvidia_version: 460