---

- name: docker, Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker, add repository
  apt_repository:
    repo: deb [arch={{ ARCH }}] https://download.docker.com/linux/ubuntu {{ LSB_RELEASE }} stable
    state: present

- name: docker, install
  apt:
    name:       
      - docker-ce 
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

  become: yes