---

- name: pre install packages
  apt:
    name: "{{ packages_preinstall }}"
    state: latest
    update_cache: yes
  become: yes

#- name: apt upgrade
#  apt:
#    upgrade: yes
#    update_cache: yes

#- name: install packages
 # apt:
#    name: "{{ packages_install }}"
#    state: latest
#    update_cache: yes
#  become: yes

- include: ./google_chrome.yml
- include: ./endpoint_verification.yml
- include: ./docker.yml